### ISSUE TITLE
False positive on G003?

### ISSUE THREAD

**Issue by steven-murray** [globality-corp/flake8-logging-format#56]
A statement like `logger.info("This is the {i+1}th iteration")` raises G003 but this is clearly not a concatenation.

**Comment by sethisernhagen** [comment]
Hi @steven-murray. I tried to repro the issue here without any luck. https://github.com/globality-corp/flake8-logging-format/blob/feature/string-concat-bug/logging_format/tests/test_visitor.py#L388-L398

**Comment by steven-murray** [comment]
Interesting. My actual line is

```python
logger.info(f"Simulating Frequency {i+1}/{len(data_model.freqs)}")
```

but I can't see anything much different in this than the one in the test. In case it matters, my pre-commit setup is:

```
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-rst-docstrings
          - flake8-builtins
          - flake8-logging-format
          - flake8-rst-docstrings
          - flake8-rst
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-print
```
