### ISSUE TITLE
Consider adding a dependency on setuptools

### ISSUE THREAD

**Issue by yakMM** [globality-corp/flake8-logging-format#68]
In `whitelist.py`, there is an import on `pkg_resources` from `setuptools`.

https://github.com/globality-corp/flake8-logging-format/blob/b7da42d1593ca19c5390be1e710439d0c45099ac/logging_format/whitelist.py#L5

This makes the code fail on environments without setuptools.

I suggest avoiding using the package altogether or making it a dependency (eventually optional)

**Comment by pfmoore** [comment]
+1 on this. In Python 3.12 neither venv nor virtualenv will install setuptools by default into environments. As a result, this will start to fail pretty soon.

**Comment by acdha** [comment]
For anyone else who's hit this with pre-commit hooks failing, simply add an explicit dependency:

```yaml
- repo:  https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
      - id: flake8
        additional_dependencies:
            - setuptools
            - flake8-logging-format
```
